CREATE TABLE inquiry (
    id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(20),
    industry VARCHAR(40),
    has_existing_website BOOLEAN DEFAULT FALSE,
    preferred_contact_method VARCHAR(40),
    status VARCHAR(40) DEFAULT 'new',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
